language: python
matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7
      addons:
        apt:
          packages:
            - bsdtar
    - name: "Python 3.6 on Linux"
      python: 3.6
      addons:
        apt:
          packages:
            - bsdtar
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11
      language: shell

install: pip3 install --upgrade pip

before_install:
  - make fetch_data download

script:
  - make test build
